# Generated by Django 3.0.8 on 2020-08-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('TaskTitle', models.CharField(max_length=50)),
                ('TaskInfo', models.TextField()),
                ('Date', models.DateTimeField()),
                ('DueDate', models.DateTimeField()),
            ],
        ),
    ]
